### ISSUE TITLE
imaging: should not use SAS solution if not reliable

### ISSUE THREAD

**Issue by FredSchuller** [i4Ds/STIX-GSW#110]
All the imaging algorithms make now use of the STIX pointing that is stored in the AUX fits files to generate maps defined in heliocentric coordinates. This pointing is derived from processing the aspect (SAS) data.

A test has already been implemented in _stx_create_auxiliary_data_ to compare this "SAS pointing" with the satellite pointing; if they differ a lot (currently the threshold is 200 arcsec) then the satellite pointing is used. But there are some cases where the difference is smaller than that, but still the SAS solution is not reliable for some reason. In such cases, at least a warning should be displayed to the user, who should have the possibility to not use the SAS solution.

**Comment by samaloney** [comment]
@FredSchuller I guess this can be closed now?
