### ISSUE TITLE
Option to semi-calibrate lightcurve data for attenuator

### ISSUE THREAD

**Issue by grazwegian** [i4Ds/STIX-GSW#127]
When the lightcurve is generated an option should exist to estimate the effect of attenuator transmission and correct for it so that lightcurves generated for publications don't show RCR step changes.

**Comment by ennosigaeus** [comment]
This was discussed in today's weekly telco:

Säm notes that Olivier has a student looking into this. He believes it is not a high priority. Therefore, we close it for now and open it up if needed.
