### ISSUE TITLE
Add stx_map2fits to the ssw software

### ISSUE THREAD

**Issue by hayesla** [i4Ds/STIX-GSW#143]
There's this code stx_fits2map.pro that available from the datacenter https://datacenter.stix.i4ds.net/pub/misc/stix_imaging/stx_map2fits.pro, however it would be nice if this were available directly through the stix ssw software.

Basically to save a STIX map to a FITS file with the correct header info

**Comment by samaloney** [comment]
Yea we should defo add some version of this but it gets complicate as the fits file position info is based on date-avg by definition, but the imaging software should be using the spice data from the actual imaging time via the aux-ephemeris files. Most of the time they should be that different but not always.

**Comment by hayesla** [comment]
do you mean the fits file position info within the original pixels file?

**Comment by samaloney** [comment]
I guess this can be closed @hayesla?

**Comment by ennosigaeus** [comment]
During the STIX co-location, we agreed that it is fixed and merged and can be closed.
