### ISSUE TITLE
If 'sumcase' is set to 'ALL' but data not present for all pixels then imaging pipeline throws an error

### ISSUE THREAD

**Issue by FredSchuller** [i4Ds/STIX-GSW#152]
There is at least one test in function `stx_sum_pixel_data` (maybe more in other places): if the actual pixel mask found in the data is not consistent with the value of 'sumcase' passed as argument, then it throws an error and stops.
The user can explicitly pass `sumcase='TOP+BOT'` as argument to some procedures, but for example not in `stx_estimate_flare_location`

A clean fix would be to change the action that results from that test, so that whatever pixels are available in the file are used instead of stopping execution.
A possibly quicker fix for 99% of the data acquired until now would be to use TOP+BOT instead of ALL as a default. This should be changed consistently (also in the comments) in all functions where it is used.
@paolomassa can you please look into that?

**Comment by samaloney** [comment]
@FredSchuller is this still an issue?

**Comment by FredSchuller** [comment]
This has been addressed some time ago.
