### ISSUE TITLE
Some functions fail when time range contains change of day

### ISSUE THREAD

**Issue by FredSchuller** [i4Ds/STIX-GSW#162]
Procedures `stx_create_auxiliary_data` and `stx_estimate_flare_location` produce an error when the input time range starts on a given day and finish on the following day.
In such a case, we need to read two successive ephemeris files and merge their content.
Also to be checked if the same problem could occur in other functions or procedures.

**Comment by paolomassa** [comment]
The same issue applies to the routines for computing the visibility values. Do you have an example of a flare that is across two days which can be used as a reference?

**Comment by FredSchuller** [comment]
@paolomassa 
An example that I've been using to fix that issue (as far as stx_create_auxiliary_data is concerned) is over the time range: ['2022-05-12T23:58:25', '2022-05-13T00:08']
