### ISSUE TITLE
STX_CONSTRUCT_CALIBRATED_VISIBILITY 

### ISSUE THREAD

**Issue by JSGH2020** [i4Ds/STIX-GSW#163]
**Short Description**

When calling STX_CONSTRUCT_CALIBRATED_VISIBILITY with an L1 file that contains only a single timebin and a timerange that covers this timebin only partially, it will crash without providing any information. I think it should either print an appropriate statement or adjust the timerange to cover the entire timebin of the L1 file.

**Details**

% TRANSPOSE: Value of <INT       Array[3]> is out of allowed range.
% Execution halted at: STX_PLOT_SELECTED_TIME_RANGE   83 C:\Program0Files\Harris\IDL86\so\stix\idl\processing\pixel_data\stx_plot_selected_time_range.pro
%                      STX_CONSTRUCT_PIXEL_DATA  181 C:\Program0Files\Harris\IDL86\so\stix\idl\processing\pixel_data\stx_construct_pixel_data.pro
%                      STX_CONSTRUCT_PIXEL_DATA_SUMMED   66 C:\Program0Files\Harris\IDL86\so\stix\idl\processing\pixel_data\stx_construct_pixel_data_summed.pro
%                      STX_CONSTRUCT_VISIBILITY   93 C:\Program0Files\Harris\IDL86\so\stix\idl\processing\vis\stx_construct_visibility.pro
%                      STX_CONSTRUCT_CALIBRATED_VISIBILITY   87 C:\Program0Files\Harris\IDL86\so\stix\idl\processing\vis\stx_construct_calibrated_visibility.pro

[exampleFiles.zip](https://github.com/i4Ds/STIX-GSW/files/11372743/exampleFiles.zip)

**Environment**
- IDL Version: 8.6.0
- STIX GSW Version: v0.4.0
- OS: W11

**Comment by paolomassa** [comment]
Thanks @JSGH2020 for reporting this issue!

I will open a pull request soon with a solution to this problem. As a temporary solution, you could set /silent when you use 'stx_construct_calibrated_visibility', so that it does not use 'stx_plot_selected_time_range'.

**Comment by samaloney** [comment]
@paolomassa do you know if this can be closed, I think so?
