### ISSUE TITLE
stx_construct_pixel_data.pro works only if both the science and the background L1 fits files contain more than 1 energy bin

### ISSUE THREAD

**Issue by paolomassa** [i4Ds/STIX-GSW#190]
This issue is related to  #185 . The current version of the software for creating a stx_pixel_data structure works only in the case when both the science and the background L1 fits files contain more than 1 energy bin. However, most probably files containing a single energy bin have never been downloaded so far.

This is not difficult to fix in principle. However, it would be good to know whether there are any L1 fits files (either a science or a background one) which contain a single energy bin for testing. Does anybody know anything about that?

**Comment by ennosigaeus** [comment]
@paolomassa will add a check and provide a message if we encounter this again. Then, it's fixed for now until it becomes a real issue.

**Comment by samaloney** [comment]
Closed in #227
