### ISSUE TITLE
IDL: FSW_sim ql accumulation for variance diverges from FSW

### ISSUE THREAD

**Issue by nicHoch** [i4Ds/STIX-GSW#20]
In the FSW a energy mask defines which energy channels are aggregated to the variance signal. An energy mask allows for ranges with gaps.

In the FSW_sim (IDL) one energy range is defined - so there are no possibilities for gaps. 

If gaps in the energy channels becomes an important requirement than the simulator code has to be adapted.

**Comment by ennosigaeus** [comment]
I will close the issue. Currently, we do not need to deal with it, and there is still a paper trail on GitHub if we need to reactivate the issue.
