### ISSUE TITLE
Errors in procedure documentation - pixel selection cases for imaging in "stx_sum_pixel_data.pro"

### ISSUE THREAD

**Issue by PaipaPsyche** [i4Ds/STIX-GSW#214]
The procedure "stx_plot_selected_time_range.pro" uses a [switch-case loop ](https://github.com/i4Ds/STIX-GSW/blob/bb8acc8accc2ec59a9cbd6e277d4098856c34a2d/stix/idl/processing/pixel_data/stx_plot_selected_time_range.pro#L116) to determine whether to use the top, bottom or all pixels for imaging ('sumcase' parameter). However [the options defined in the documentation](https://github.com/i4Ds/STIX-GSW/blob/bb8acc8accc2ec59a9cbd6e277d4098856c34a2d/stix/idl/processing/pixel_data/stx_sum_pixel_data.pro#L22) of "stx_sum_pixel_data.pro" do not coincide entirely with the functional cases. I don't know if this happens in other files.

**Comment by samaloney** [comment]
@paolomassa / @FredSchuller thoughts, I quickly looked at the code but don't see a difference/problem?

**Comment by paolomassa** [comment]
Not sure what is the problem here. @PaipaPsyche could you please give us more information about this bug? Thanks!

**Comment by PaipaPsyche** [comment]
I used a wrong tag, more than a bug I think is misleading documentation: I wanted to use just the bottom pixels for imaging, so I tried using the 'BOTTOM' key in the sumacase parameter as suggested by the documentation of "stx_sum_pixel_data.pro"(line 25).  But it doesn't work, as the case 'BOTTOM' is not contemplated as an option in the switch case of   "stx_plot_selected_time_range.pro" (line 116), the expected keyword for using  bottom pixels is 'BOT'.

**Comment by FredSchuller** [comment]
This is solved with PR #225
