### ISSUE TITLE
Problems with the L1 fits files on pub099

### ISSUE THREAD

**Issue by paolomassa** [i4Ds/STIX-GSW#43]
I tried to use the L1 fits files on pub099 for reconstructing the images, but I found the following issues in the 'stix_l1_read' procedure:

1) line 10 doesn't work properly; I think that changing "energy = mrdfits(sci_file, 3, energy_header)" with "energy = mrdfits(sci_file, 4, energy_header)" should fix this.
2) line 34: "cccc" has dimension [32, 8, 32, 45] instead of [32, 12, 32, 45]. Was the content of the 4 small pixels removed in these fits files?
3) if I fix 1) and 2) the routine doesn't crash anymore, but it gives unreasonable values for the count rates. I suspect that the problem is in the 'triggers32' variable (defined in line 21 of 'stix_l1_read'). Indeed, the entries of this variable contain values close to -9.8e18, which are quite strange.

If I have understood correctly the problems in 1) and 2) the modifications to be done are very simple. However, I don't know how to fix 3).

**Comment by samaloney** [comment]
@paolomassa can this be closed?

**Comment by paolomassa** [comment]
Yes, I think so. This issue was opened before the big change to the imaging pipeline in fall 2022. We do not have problems anymore in reading fits files.
