### ISSUE TITLE
Version.txt not in SSW distro 

### ISSUE THREAD

**Issue by grazwegian** [i4Ds/STIX-GSW#69]
Wanted to check if the new version of stx_gsw_version worked in the updated v0.1 but after running ssw_upgrade there was no VERSION.txt file in the /stix folder. Checking the archive on https://soho.nascom.nasa.gov/solarsoft/offline/swmaint/tar/ it doesn't appear to be there either but it is present in https://datacenter.stix.i4ds.net/pub/ssw/stix/latest/.

**Comment by ennosigaeus** [comment]
![image](https://user-images.githubusercontent.com/649330/165048232-c9755540-bd99-4549-92d6-928af09da6c7.png)

Did you notice that the file dates don't match up?

LMSAL: March 25
FHNW: March 31

**Comment by ennosigaeus** [comment]
I also see files with the timestamp on March 28, but none are on March 31.

**Comment by ennosigaeus** [comment]
I also just saw that "date" and "last-modified" show when files were created and last modified:

```
laszlo@surfacebook3-lie:~$ curl -I https://datacenter.stix.i4ds.net/pub/ssw/stix/latest/stix/idl/pipeline/stx_software_framework.pro
HTTP/1.1 200 OK
Server: nginx/1.18.0 (Ubuntu)
Date: Mon, 25 Apr 2022 08:36:10 GMT
Content-Type: application/octet-stream
Content-Length: 3654
Last-Modified: Thu, 31 Mar 2022 12:58:53 GMT
Connection: keep-alive
ETag: "6245a58d-e46"
Accept-Ranges: bytes
```

**Comment by ennosigaeus** [comment]
I copied all files from LMSAL and FHNW and ran a comparison. The results:

```
laszlo@surfacebook3-lie:~/comp$ colordiff -qur stix_*
Only in stix_fhnw/stix: VERSION.txt
Only in stix_fhnw/stix/idl/demo: stx_ospex_spectroscopy_demo.pro
Files stix_fhnw/stix/idl/processing/imaging/stx_vis_fwdfit_pso.pro and stix_lmsal/stix/idl/processing/imaging/stx_vis_fwdfit_pso.pro differ
Only in stix_fhnw/stix/idl/util: stx_gsw_github_development.pro
```

The lines I ran:
```
wget -r -np -R "index.html*" -e robots=off https://datacenter.stix.i4ds.net/pub/ssw/stix/latest/
wget -r -np -R "index.html*" -e robots=off https://www.lmsal.com/solarsoft/ssw/so/stix_latest/

# copy the "stix" folders inside "latest" and "stix_latest" to "fhnw_stix" and "lmsal_stix"
colordiff -qurN stix_*
```

**Comment by samaloney** [comment]
there's also the soho site which seem different again and I think is the default SSW mirror https://soho.nascom.nasa.gov/solarsoft/so/stix/

**Comment by ennosigaeus** [comment]
I just received a message from Sam Freeland. It seems the sync process halted on March 28ish. We looked into it and Sam thinks it’s due to a network firewall change.

I’ll keep you posted.

**Comment by grazwegian** [comment]
Yes, the soho site is where I was initially checking and is used as default by ssw_upgrade.

**Comment by ennosigaeus** [comment]
I got feedback that the new distribution fix worked (it seems a network change at LMSAL was the problem). I'm closing the issue.
