### ISSUE TITLE
project workflow is undefined

### ISSUE THREAD

**Issue by rschwartz70** [i4Ds/STIX-GSW#8]
I have many questions about how  we are supposed to work with the STIX-GSW repository.  What has been described is a procedure for downloading the current Master repository and having those directories appear in the IDL path.  This leaves many unanswered issues about software development.
1. If we have a clone of the Master within our IDL path what happens when we change a file locally. Do we save it into our local Master?  If so is our Desktop github recording all the file changes?  Do we save it into a local directory not under the cloned Master? 
2. How do we upload our changes to the repository?  We can't load them into the master. I have created a branch and loaded them there.  Is this correct?  
3. Are any of the developer branches getting merged into the master?  If not, why not?
4. When and where does Git record the file changes? 

I bet I have many more questions but not knowing the answers to these questions makes me unable to pose them.  I get the feeling that I'm knocking on the door and no one is home.

**Comment by ennosigaeus** [comment]
I feel the project workflow is now better understood and documented on the main page. Closing this issue.
