### ISSUE TITLE
Use same live time correction in both imaging and spectroscopy

### ISSUE THREAD

**Issue by samaloney** [i4Ds/STIX-GSW#82]
**Is your feature request related to a problem? Please describe.**
I know this is probably already being worked on but  just noting it down but the current imaging demo use it own version of the live time correction.

https://github.com/i4Ds/STIX-GSW/blob/5f5bf12c7bbdef7004370f76dcbeea8a999a5ef8/stix/idl/processing/vis/stix_l1_read.pro#L51-L68

should use the same code https://github.com/i4Ds/STIX-GSW/blob/5f5bf12c7bbdef7004370f76dcbeea8a999a5ef8/stix/idl/processing/livetime/stx_livetime_fraction.pro which has been updated to include a pileup correction too.

**Comment by grazwegian** [comment]
@paolomassa is this solved in the imaging pipeline rewrite?

**Comment by paolomassa** [comment]
Yes, in the new version of the imaging pipeline, I construct a triggergram with 'stx_triggergram(data.TRIGGERS, t_axis)' and then I give it as input to 'stx_livetime_fraction' (see lines 155-161 in 'stx_construct_pixel_data') for computing the live time fraction, as suggested by @samaloney
