### ISSUE TITLE
Map keywords

### ISSUE THREAD

**Issue by samaloney** [i4Ds/STIX-GSW#97]
Currently if you write out maps from the imaging system e.g. `map2fits mom_map` the headers are incomplete and don't have the necessary info to work in sunpy for examples. Also an option to not rotate the maps and set the proper header keywords would be useful

**Comment by FredSchuller** [comment]
There is a procedure ` stx_map2fits` that is available here: https://datacenter.stix.i4ds.net/pub/misc/stix_imaging/
It may (or maybe not...) fix this issue.

I don't know why it's not included in the GSW repo.

**Comment by samaloney** [comment]
I'm going to close as mentioned procedure is now included
